import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "../globals.css"

import NavBar from "./components/navBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  todo,
  inProgress,
  done,
}: {
  children: React.ReactNode
  todo: React.ReactNode
  inProgress: React.ReactNode
  done: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="flex min-h-screen justify-center bg-blue-100 p-24 text-black">
          <div className="z-10 w-full max-w-5xl text-sm ">
            <div className="grid grid-cols-12 justify-items-start gap-3">
              {todo}
              {inProgress}
              {done}
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
